[web]
worker-node-1 ansible_host=35.90.235.60

[app]
worker-node-2 ansible_host=18.236.209.160

[application:children]
web
app

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/terraform-module/deployer_key
ansible_python_interpreter=/usr/bin/python3